#!/usr/bin/fish

set base "/base"
set logs "/logs"
set arch "$base/.subs.archive"
set conf "$base/.subs.conf"
set lock "$base/.ytcron.pid"
set logg "$logs/ytcron.log"
touch $logg

echo "Sourcing $conf for configuration."
source $conf
echo "Configuration complete."

if test ! -d $base
    echo "$0: base directory $base doesn't exist, bailing."
    exit -1
end

if test -f $lock
    echo "$0: lock $lock exists, bailing."
    exit -2
end
echo %self > $lock

function get_single_source
    set -l dir $argv[1]
    set -l vid $argv[2]
    echo '================================================================================'
    echo "===== $vid"
    echo '================================================================================'
    youtube-dl -i \
        --output "$base/$dir/%(title)s-%(id)s.%(ext)s" \
        --download-archive $arch \
        --reject-title $reject \
        --max-downloads $per \
        --playlist-end $max \
        --rate-limit $rate \
        --format $fmt \
        --all-subs \
        --write-thumbnail \
        $vid
    echo '================================================================================'
    sleep 15
end

echo "Base directory exists; lockfile not present."
echo "Starting download of one-offs."

for el in (construct_vids)
    get_single_source '[queue]' $el >> $logg
end

echo "Starting download of subscriptions."

for el in (construct_subs)
    get_single_source '%(uploader_id)s' $el >> $logg
end

echo "Done, removing lock."

rm $lock

echo "Bye!"
